version: "3"

services:
  backend:
    container_name: backend
    restart: always
    build: backend/.
    environment:
      - DB_HOST=172.19.0.4
      - DB_USER=admin
      - DB_PASS=Test_1234_
      - DB_DATABASE=Racks
    ports:
      - "3000:3000"
    networks:
      app-net:
        ipv4_address: 172.19.0.2

  database:
    container_name: database
    restart: always
    build: database/.
    ports:
      - "3306:3306"
    volumes:
      - db-tp7:/var/lib/mysql
    networks:
      app-net:
        ipv4_address: 172.19.0.3

networks:
  app-net:
    ipam:
      driver: default
      config:
        - subnet: "172.19.0.0/24"

volumes:
  db-tp7:
